---
- name: Restart MegaProxy GOST
  ansible.builtin.systemd_service:
    name: megaproxy-gost
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode

- name: Restart MegaProxy HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
  when: not ansible_check_mode
