---
- name: Validate and reload ssh
  ansible.builtin.command: sshd -t
  changed_when: false
  notify: Reload ssh

- name: Reload ssh
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
  when: not ansible_check_mode
