---
- name: Install common packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: >-
      {{
        [
          'ca-certificates',
          'curl',
          'openssl',
          'sudo',
          'openssh-server',
          'systemd-timesyncd',
          'ufw',
          'fail2ban',
          'unattended-upgrades'
        ]
        + (['docker.io'] if megaproxy_services.https is defined and megaproxy_services.https.enabled else [])
        + (['haproxy'] if megaproxy_services.https is defined and megaproxy_services.https.enabled else [])
      }}
    state: present
    lock_timeout: 600

- name: Enable time synchronization
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true
    state: started
  when:
    - ansible_facts["service_mgr"] == "systemd"
    - ansible_facts["virtualization_type"] != "lxc"

- name: Enable unattended upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    enabled: true
    state: started
  when: megaproxy_settings.unattended_upgrades | bool

- name: Create journald configuration directory
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Limit persistent journal disk usage
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf.d/60-megaproxy-limits.conf
    content: |
      [Journal]
      SystemMaxUse=500M
      SystemMaxFileSize=100M
      SystemMaxFiles=100
      SystemKeepFree=100M
    owner: root
    group: root
    mode: "0644"
  notify: Restart journald
